# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1krvv6rr0yfh8n81b9cgp1s72c40ys9cz0bnnsbspavlfnw9vgr4";
    aarch64-linux = "1j0fb817jpfmnmwypfffpg23y2i4830a8r8ql4jyxgw4chh80ldy";
    x86_64-darwin = "0wfcsdydb7f9lm8lbzblvqwg82qp9hlxs4n7vhhn0c2v7c5n52bb";
    aarch64-darwin = "1qrimqhp3q2dxww8xrflqj1y4z3vdx96w5xssh2l1x2xfgahz57s";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/vodarr/releases/download/v0.1.0/vodarr_0.1.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/vodarr/releases/download/v0.1.0/vodarr_0.1.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/vodarr/releases/download/v0.1.0/vodarr_0.1.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/vodarr/releases/download/v0.1.0/vodarr_0.1.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "vodarr";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./vodarr $out/bin/vodarr
    wrapProgram $out/bin/vodarr --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/vodarr/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Downloads movies and series from video-on-demand sites for Sonarr and Radarr.";
    homepage = "https://github.com/combor/vodarr";
    license = lib.licenses.bsd3;
    mainProgram = "vodarr";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
