# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "14rhczj6bjqw9bax04dzbqjb8cmcm0x4zvpjqpr2n3xx1x0fryg1";
    aarch64-linux = "0m93bi3071ksczlhrk03q9psxa74i52k2l5j8z0ln8airvh6vnhh";
    x86_64-darwin = "0qfpp120kpb4d3nxc5df4ihlkkj69wq0qszxsa9d98wp8ccd3j4x";
    aarch64-darwin = "042y0jxqx4vpfpn8nbh30fd1wjrg5rn5j571r4s8b2f27dk6wbyx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/vodarr/releases/download/v0.2.0/vodarr_0.2.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/vodarr/releases/download/v0.2.0/vodarr_0.2.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/vodarr/releases/download/v0.2.0/vodarr_0.2.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/vodarr/releases/download/v0.2.0/vodarr_0.2.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "vodarr";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./vodarr $out/bin/vodarr
    wrapProgram $out/bin/vodarr --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/vodarr/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Downloads movies and series from video-on-demand sites for Sonarr and Radarr.";
    homepage = "https://github.com/combor/vodarr";
    license = lib.licenses.bsd3;
    mainProgram = "vodarr";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
