# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1x1lwrdlfk6y04lr8mfks3m7ch4yx3pvydlsyci92l1iwvwb1h51";
    aarch64-linux = "0kxs9sgjkhd679k44kh84nb94m38nqw6yvg3s1flfrr0ppgw39cw";
    x86_64-darwin = "1idb0qazg1r8inigwmcaycmk2kwgzn52pz6qiz6hml3xsjgw1l3y";
    aarch64-darwin = "0mvmx9hgpd596kqflwscnz8hrksch32gciy6w0mpbl3av9krx0q6";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/magnetowid/releases/download/v0.3.0/magnetowid_0.3.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/magnetowid/releases/download/v0.3.0/magnetowid_0.3.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/magnetowid/releases/download/v0.3.0/magnetowid_0.3.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/magnetowid/releases/download/v0.3.0/magnetowid_0.3.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "magnetowid";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./magnetowid $out/bin/magnetowid
    wrapProgram $out/bin/magnetowid --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/magnetowid/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Downloads movies and series from video-on-demand sites for Sonarr and Radarr.";
    homepage = "https://github.com/combor/magnetowid";
    license = lib.licenses.bsd3;
    mainProgram = "magnetowid";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
