# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1h2qddf2ifqinq0s1abmxwwiad6s6a92qimaamhqfc4zg6fsa13s";
    aarch64-linux = "0qn820ssqdk3qz3b09157015kgrawns0l5vjlr0v2v0dddf7w8ja";
    x86_64-darwin = "17w2a4yjl5yl2wcbijc5a8b993fv7lczw9nhcvgi7nkbhr8xzf3c";
    aarch64-darwin = "0y5zb1365l8dm8j7011an38cym9qb72f31ziji44k5vggyz2kaa9";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/magnetowid/releases/download/v0.2.1/magnetowid_0.2.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/magnetowid/releases/download/v0.2.1/magnetowid_0.2.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/magnetowid/releases/download/v0.2.1/magnetowid_0.2.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/magnetowid/releases/download/v0.2.1/magnetowid_0.2.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "magnetowid";
  version = "0.2.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./magnetowid $out/bin/magnetowid
    wrapProgram $out/bin/magnetowid --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/magnetowid/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Downloads movies and series from video-on-demand sites for Sonarr and Radarr.";
    homepage = "https://github.com/combor/magnetowid";
    license = lib.licenses.bsd3;
    mainProgram = "magnetowid";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
