# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "06srghi7mfvyl4bh4wwy073ydqirfzfdmh9wz1bz952x7nzfgxfq";
    aarch64-linux = "0knhwjr4rqr54kj88rmas4wpc644q1vbpf3pqbqixnw1kl0066vf";
    x86_64-darwin = "01lzwiiqf08by6nplfvy1w6snx4p47j9d6j8cc5gvlj3yv935q5h";
    aarch64-darwin = "1j0m034gfi0iic02khsfk3i4hjnqdkkkvj65bka0wgbplx7fnplx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/magnetowid/releases/download/v0.3.1/magnetowid_0.3.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/magnetowid/releases/download/v0.3.1/magnetowid_0.3.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/magnetowid/releases/download/v0.3.1/magnetowid_0.3.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/magnetowid/releases/download/v0.3.1/magnetowid_0.3.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "magnetowid";
  version = "0.3.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./magnetowid $out/bin/magnetowid
    wrapProgram $out/bin/magnetowid --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/magnetowid/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Downloads movies and series from video-on-demand sites for Sonarr and Radarr.";
    homepage = "https://github.com/combor/magnetowid";
    license = lib.licenses.bsd3;
    mainProgram = "magnetowid";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
