# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "117y4wj0mb1grchm07h7qqk5kmh57mhxgbb0hfh84r3n9janvlk5";
    aarch64-linux = "0wkc4dj5ri39116y9ai1156i0vzil0bcq5il910xigly6vvf22n0";
    x86_64-darwin = "079p418grjsri3mbrpq2bbrjbzbbggvpifpsjq091hcliyrdhmw8";
    aarch64-darwin = "1kqg9288x9knl1mvwypq5vd2axp0phjs9zy7bdm5ma4rkkvnb5gg";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/telesfor/releases/download/v0.3.0/telesfor_0.3.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/telesfor/releases/download/v0.3.0/telesfor_0.3.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/telesfor/releases/download/v0.3.0/telesfor_0.3.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/telesfor/releases/download/v0.3.0/telesfor_0.3.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "telesfor";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./telesfor $out/bin/telesfor
    wrapProgram $out/bin/telesfor --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/telesfor/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Live TV from streaming services in Plex, as a virtual HDHomeRun tuner.";
    homepage = "https://github.com/combor/telesfor";
    license = lib.licenses.bsd3;
    mainProgram = "telesfor";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
