# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "18pws2x2pxk2xa4j6ylryfhg5k050vwc9wzklfz76nb455mj97px";
    aarch64-linux = "13xym967x9n7mr79gyvrn7b25jzqas0yn5gxkj2a74x5xdls911g";
    x86_64-darwin = "1zq5ycxs77x6a7yjncb634yrf4364z7m78nwwprjkz7m4q9vhpa6";
    aarch64-darwin = "09bgmkl26hisqisylrkz7m5ygmqramlwdalvbgsbxc686hamlphb";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/telesfor/releases/download/v0.3.1/telesfor_0.3.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/telesfor/releases/download/v0.3.1/telesfor_0.3.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/telesfor/releases/download/v0.3.1/telesfor_0.3.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/telesfor/releases/download/v0.3.1/telesfor_0.3.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "telesfor";
  version = "0.3.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./telesfor $out/bin/telesfor
    wrapProgram $out/bin/telesfor --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/telesfor/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Live TV from streaming services in Plex, as a virtual HDHomeRun tuner.";
    homepage = "https://github.com/combor/telesfor";
    license = lib.licenses.bsd3;
    mainProgram = "telesfor";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
