# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "18znymg7s6h5j4xq5zjf1sfd5l5cic5mfycsilxz196scwx23x41";
    aarch64-linux = "0pivgwc8q113vvxicz9129l66zlv4gniag35vqd72dn0d3lairjg";
    x86_64-darwin = "0vzgrq6k5z5ax2448i34pq1l0x6dx8dlgmhxjgi3j1y59b067nnd";
    aarch64-darwin = "0rlpyawxnbqp1wq81j10hz03751xjvgnrpmybfqf10bkyr30szzx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/telesfor/releases/download/v0.2.3/telesfor_0.2.3_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/telesfor/releases/download/v0.2.3/telesfor_0.2.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/telesfor/releases/download/v0.2.3/telesfor_0.2.3_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/telesfor/releases/download/v0.2.3/telesfor_0.2.3_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "telesfor";
  version = "0.2.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./telesfor $out/bin/telesfor
    wrapProgram $out/bin/telesfor --prefix PATH : ${lib.makeBinPath ([ ffmpeg ])}
    install -Dm644 ./LICENSE "$out/share/licenses/telesfor/LICENSE"
    runHook postInstall
  '';

  meta = {
    description = "Live TV from streaming services in Plex, as a virtual HDHomeRun tuner.";
    homepage = "https://github.com/combor/telesfor";
    license = lib.licenses.bsd3;
    mainProgram = "telesfor";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
