# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1abbzl5077nzsxbcx3m92hr6bgah8birpqlwapa9pxda3vphh1n9";
    aarch64-linux = "1y8r6kiwzj8vc20zpi68kjfm3ki0nd887354q6l5c3ng57jacc1q";
    x86_64-darwin = "1zia8c67slpl4m9gdw3g5ql2jypp2ia19zaypdc3piyx3xcvy54b";
    aarch64-darwin = "0rbcm5ngsgmivn4hh4b8qp8p1mrini4kxhxhmvypda03jmmffhbg";
  };

  urlMap = {
    x86_64-linux = "https://github.com/combor/baryon-mcp/releases/download/v0.6.3/baryon-mcp_0.6.3_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/combor/baryon-mcp/releases/download/v0.6.3/baryon-mcp_0.6.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/combor/baryon-mcp/releases/download/v0.6.3/baryon-mcp_0.6.3_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/combor/baryon-mcp/releases/download/v0.6.3/baryon-mcp_0.6.3_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "baryon-mcp";
  version = "0.6.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./baryon-mcp $out/bin/baryon-mcp
    runHook postInstall
  '';

  meta = {
    description = "Read Proton Mail and save drafts through your local Proton Mail Bridge.";
    homepage = "https://github.com/combor/baryon-mcp";
    license = lib.licenses.bsd3;
    mainProgram = "baryon-mcp";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
